package Vista;

import Controlador.ControladorPersona;
import Excepciones.DAO_Excep;
import Excepciones.excepcionCliente;
import Excepciones.excepcionEmpleado;
import Excepciones.excepcionPersona;
import Modelo.Cliente;
import Modelo.Empleado;
import Modelo.Persona;
import Modelo.Vehiculo;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class DarAlta extends javax.swing.JDialog {

    CardLayout vehiculoLayout;
    CardLayout cLayout;
    Vehiculo vehiculo = null;

    /**
     * Creates new form DarAlta
     */
    public DarAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        vehiculoLayout = (CardLayout) (panelVehiculo.getLayout());
        cLayout = (CardLayout) (panelEspecifico.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGenero = new javax.swing.ButtonGroup();
        grupoTipo = new javax.swing.ButtonGroup();
        grupoVIP = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        panelVehiculo = new javax.swing.JPanel();
        panelVehiculoNo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        panelVehiculoSi = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelEspecifico = new javax.swing.JPanel();
        panelEmpleado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        inputIDempleado = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        inputSueldo = new javax.swing.JSpinner();
        panelCliente = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        inputIDcliente = new javax.swing.JSpinner();
        noVIP = new javax.swing.JRadioButton();
        siVIP = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        inputDNI = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        inputNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        inputDireccion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        inputEmpleado = new javax.swing.JRadioButton();
        inputCliente = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        inputFem = new javax.swing.JRadioButton();
        inputMasc = new javax.swing.JRadioButton();
        inputOtro = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        inputEdad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(248, 245, 245));
        panelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1275, 785));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("DAR DE ALTA");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Introduzca los datos de la");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("persona para dar de alta.");

        panelDatos.setBackground(new java.awt.Color(248, 245, 245));

        panelVehiculo.setBackground(new java.awt.Color(248, 245, 245));
        panelVehiculo.setLayout(new java.awt.CardLayout());

        panelVehiculoNo.setBackground(new java.awt.Color(248, 245, 245));

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 102));
        jLabel16.setText("Vehículo");

        btnAdd.setBackground(new java.awt.Color(248, 245, 245));
        btnAdd.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnAdd.setText("Añadir");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVehiculoNoLayout = new javax.swing.GroupLayout(panelVehiculoNo);
        panelVehiculoNo.setLayout(panelVehiculoNoLayout);
        panelVehiculoNoLayout.setHorizontalGroup(
            panelVehiculoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        panelVehiculoNoLayout.setVerticalGroup(
            panelVehiculoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoNoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelVehiculoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnAdd))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        panelVehiculo.add(panelVehiculoNo, "card2");

        panelVehiculoSi.setBackground(new java.awt.Color(248, 245, 245));

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 102));
        jLabel15.setText("Vehículo");

        jSeparator25.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator25.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jSeparator26.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator26.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Vehículo registrado.");

        jLabel23.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Al registrar la persona se vincularán estos datos.");

        javax.swing.GroupLayout panelVehiculoSiLayout = new javax.swing.GroupLayout(panelVehiculoSi);
        panelVehiculoSi.setLayout(panelVehiculoSiLayout);
        panelVehiculoSiLayout.setHorizontalGroup(
            panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 274, Short.MAX_VALUE)
                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 274, Short.MAX_VALUE)))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 274, Short.MAX_VALUE)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 274, Short.MAX_VALUE)))
        );
        panelVehiculoSiLayout.setVerticalGroup(
            panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVehiculoSiLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(139, 139, 139))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 124, Short.MAX_VALUE)))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 124, Short.MAX_VALUE)))
        );

        panelVehiculo.add(panelVehiculoSi, "panelVehiculoSi");

        panelEspecifico.setLayout(new java.awt.CardLayout());

        panelEmpleado.setBackground(new java.awt.Color(248, 245, 245));

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 102));
        jLabel9.setText("Datos específicos");

        inputIDempleado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputIDempleado.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        inputIDempleado.setBorder(null);

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("ID");

        jLabel21.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Sueldo");

        inputSueldo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputSueldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        inputSueldo.setBorder(null);

        javax.swing.GroupLayout panelEmpleadoLayout = new javax.swing.GroupLayout(panelEmpleado);
        panelEmpleado.setLayout(panelEmpleadoLayout);
        panelEmpleadoLayout.setHorizontalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(panelEmpleadoLayout.createSequentialGroup()
                        .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(79, 79, 79)
                        .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(inputSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        panelEmpleadoLayout.setVerticalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel20)
                        .addGap(27, 27, 27)
                        .addComponent(inputIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmpleadoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel21)
                        .addGap(24, 24, 24)
                        .addComponent(inputSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        panelEspecifico.add(panelEmpleado, "panelEmpleado");

        panelCliente.setBackground(new java.awt.Color(248, 245, 245));
        panelCliente.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(255, 204, 102));
        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 102));
        jLabel10.setText("Datos específicos");

        inputIDcliente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputIDcliente.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        inputIDcliente.setBorder(null);

        grupoVIP.add(noVIP);
        noVIP.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        noVIP.setToolTipText("");
        noVIP.setBorder(null);
        noVIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NO_noSelect.png"))); // NOI18N
        noVIP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/NO_select.png"))); // NOI18N

        grupoVIP.add(siVIP);
        siVIP.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        siVIP.setSelected(true);
        siVIP.setToolTipText("");
        siVIP.setBorder(null);
        siVIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_noSelect.png"))); // NOI18N
        siVIP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_select.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("ID");

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("VIP");

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(79, 79, 79)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(siVIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noVIP)))))
                .addContainerGap())
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(26, 26, 26)
                        .addComponent(inputIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noVIP)
                            .addComponent(siVIP))))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        panelEspecifico.add(panelCliente, "panelCliente");

        btnRegistrar.setBackground(new java.awt.Color(255, 204, 102));
        btnRegistrar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistrar.setText("Registrar persona");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        inputDNI.setBackground(new java.awt.Color(248, 245, 245));
        inputDNI.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputDNI.setText("DNI");
        inputDNI.setToolTipText("DNI");
        inputDNI.setBorder(null);
        inputDNI.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDNIActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inputNombre.setBackground(new java.awt.Color(248, 245, 245));
        inputNombre.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputNombre.setText("Nombre");
        inputNombre.setToolTipText("Nombre");
        inputNombre.setBorder(null);
        inputNombre.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inputDireccion.setBackground(new java.awt.Color(248, 245, 245));
        inputDireccion.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputDireccion.setText("Dirección");
        inputDireccion.setToolTipText("Direccion");
        inputDireccion.setBorder(null);
        inputDireccion.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDireccionActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Tipo");

        grupoTipo.add(inputEmpleado);
        inputEmpleado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputEmpleado.setSelected(true);
        inputEmpleado.setToolTipText("");
        inputEmpleado.setBorder(null);
        inputEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Empleado_noSelect.png"))); // NOI18N
        inputEmpleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Empleado_select.png"))); // NOI18N
        inputEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmpleadoActionPerformed(evt);
            }
        });

        grupoTipo.add(inputCliente);
        inputCliente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputCliente.setToolTipText("");
        inputCliente.setBorder(null);
        inputCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inputCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente_noSelect.png"))); // NOI18N
        inputCliente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente_select.png"))); // NOI18N
        inputCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClienteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Género");

        grupoGenero.add(inputFem);
        inputFem.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputFem.setSelected(true);
        inputFem.setToolTipText("");
        inputFem.setBorder(null);
        inputFem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FEM_noSelect.png"))); // NOI18N
        inputFem.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/FEM_select.png"))); // NOI18N

        grupoGenero.add(inputMasc);
        inputMasc.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputMasc.setToolTipText("");
        inputMasc.setBorder(null);
        inputMasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MASC_noSelect.png"))); // NOI18N
        inputMasc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MASC_select.png"))); // NOI18N

        grupoGenero.add(inputOtro);
        inputOtro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputOtro.setToolTipText("");
        inputOtro.setBorder(null);
        inputOtro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OTRO_noSelect.png"))); // NOI18N
        inputOtro.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/OTRO_select.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Edad");

        inputEdad.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputEdad.setModel(new javax.swing.SpinnerNumberModel(16, 16, 100, 1));
        inputEdad.setBorder(null);

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 102));
        jLabel6.setText("Datos generales");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(inputFem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputMasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputOtro))
                            .addComponent(inputEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)))
                    .addComponent(jLabel13)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(inputEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCliente)))
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(26, 26, 26)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputOtro)
                                    .addComponent(inputMasc)
                                    .addComponent(inputFem)))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(inputDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(inputEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputEmpleado)
                            .addComponent(inputCliente)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(panelEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (vehiculo == null) {
            RegistrarVehiculo regVehiculo = new RegistrarVehiculo(this, true);
            regVehiculo.setLocationRelativeTo(this);
            regVehiculo.setVisible(true);

            vehiculo = regVehiculo.obtenerVehiculo();
        } else {
            vehiculoLayout.show(panelVehiculo, "panelVehiculoSi");
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked

    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String DNI = inputDNI.getText();
        String nombre = inputNombre.getText();
        String direccion = inputDireccion.getText();

        if (DNI.isEmpty() || nombre.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se pueden dejar campos en blanco.", "Datos vacíos", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                try {
                    DNI = ControladorPersona.validarDNI(DNI);
                } catch (DAO_Excep ex) {
                    Logger.getLogger(DarAlta.class.getName()).log(Level.SEVERE, null, ex);
                }

                int edad = (int) inputEdad.getValue();

                char genero = 0;
                if (inputFem.isSelected()) {
                    genero = 'f';
                } else if (inputMasc.isSelected()) {
                    genero = 'm';
                } else if (inputOtro.isSelected()) {
                    genero = 'o';
                }

                //----------------------------------------------------------------------
                if (inputEmpleado.isSelected()) {
                    int ID_EMPLEADO = (int) inputIDempleado.getValue();
                    double sueldo = (double) inputSueldo.getValue();

                    Empleado e = new Empleado(ID_EMPLEADO, sueldo, DNI, nombre, genero, edad, direccion, vehiculo);

                    try {
                        try {
                            ControladorPersona.altaEmpleado(e);
                        } catch (DAO_Excep ex) {
                            Logger.getLogger(DarAlta.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        JOptionPane.showMessageDialog(this, "La persona ha sido dada de alta.", "Registro de persona", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    } catch (excepcionEmpleado ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en el registro.", JOptionPane.ERROR_MESSAGE);
                    }

                } else if (inputCliente.isSelected()) {
                    int ID_CLIENTE = (int) inputIDcliente.getValue();

                    boolean vip = false;
                    if (siVIP.isSelected()) {
                        vip = true;
                    } else if (noVIP.isSelected()) {
                        vip = false;
                    }

                    LocalDate fechaRegistro = LocalDate.now();

                    Cliente c = new Cliente(ID_CLIENTE, fechaRegistro, vip, DNI, nombre, genero, edad, direccion, vehiculo);

                    try {
                        try {
                            ControladorPersona.altaCliente(c);
                        } catch (DAO_Excep ex) {
                            Logger.getLogger(DarAlta.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        JOptionPane.showMessageDialog(this, "La persona ha sido dada de alta.", "Registro de persona", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    } catch (excepcionCliente ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en el registro.", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (excepcionPersona ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en el registro.", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void inputDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDNIActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionActionPerformed

    private void inputEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmpleadoActionPerformed
        cLayout.show(panelEspecifico, "panelEmpleado");
    }//GEN-LAST:event_inputEmpleadoActionPerformed

    private void inputClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClienteActionPerformed
        cLayout.show(panelEspecifico, "panelCliente");
    }//GEN-LAST:event_inputClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup grupoGenero;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.ButtonGroup grupoVIP;
    private javax.swing.JRadioButton inputCliente;
    private javax.swing.JTextField inputDNI;
    private javax.swing.JTextField inputDireccion;
    private javax.swing.JSpinner inputEdad;
    private javax.swing.JRadioButton inputEmpleado;
    private javax.swing.JRadioButton inputFem;
    private javax.swing.JSpinner inputIDcliente;
    private javax.swing.JSpinner inputIDempleado;
    private javax.swing.JRadioButton inputMasc;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JRadioButton inputOtro;
    private javax.swing.JSpinner inputSueldo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton noVIP;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEmpleado;
    private javax.swing.JPanel panelEspecifico;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVehiculo;
    private javax.swing.JPanel panelVehiculoNo;
    private javax.swing.JPanel panelVehiculoSi;
    private javax.swing.JRadioButton siVIP;
    // End of variables declaration//GEN-END:variables
}
