/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ControladorPersona;
import Excepciones.DAO_Excep;
import Excepciones.excepcionPersona;
import Modelo.Cliente;
import Modelo.Empleado;
import Modelo.Persona;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pl2023290
 */
public class DarBaja extends javax.swing.JDialog {

    CardLayout vehiculoLayout;
    CardLayout tipoLayout;

    Persona personaSeleccionada;

    /**
     * Creates new form darBaja
     */
    public DarBaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            for (Persona p : ControladorPersona.getPersonas()) {
                inputBuscar.addItem(p.getDNI());
            }
        } catch (DAO_Excep ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error.", JOptionPane.ERROR_MESSAGE);
        }

        vehiculoLayout = (CardLayout) (panelVehiculo.getLayout());
        tipoLayout = (CardLayout) (panelEspecifico.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGenero = new javax.swing.ButtonGroup();
        grupoVIP = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        inputBuscar = new javax.swing.JComboBox<>();
        panelDatos = new javax.swing.JPanel();
        btnNombre = new javax.swing.JButton();
        btnDireccion = new javax.swing.JButton();
        btnEdad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        inputDireccion = new javax.swing.JTextField();
        inputDNI = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnDNI = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        inputEdad = new javax.swing.JSpinner();
        inputMasc = new javax.swing.JRadioButton();
        inputOtro = new javax.swing.JRadioButton();
        inputFem = new javax.swing.JRadioButton();
        btnGenero = new javax.swing.JButton();
        panelVehiculo = new javax.swing.JPanel();
        panelVehiculoSi = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        inputMatricula3 = new javax.swing.JTextField();
        btnMatriculaSI = new javax.swing.JButton();
        btnAntiguedadSi = new javax.swing.JButton();
        inputAntiguedadSi = new javax.swing.JSpinner();
        panelVehiculoNo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelEspecifico = new javax.swing.JPanel();
        panelEmpleado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        inputIDempleado = new javax.swing.JSpinner();
        btnID1 = new javax.swing.JButton();
        btnSueldo = new javax.swing.JButton();
        inputSueldo = new javax.swing.JSpinner();
        panelCliente = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnID2 = new javax.swing.JButton();
        inputIDcliente = new javax.swing.JSpinner();
        btnVIP = new javax.swing.JButton();
        noVIP = new javax.swing.JRadioButton();
        siVIP = new javax.swing.JRadioButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(248, 245, 245));
        panelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1275, 785));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("DAR DE BAJA");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Escoja la persona que");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("quiera dar de baja.");

        btnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(248, 245, 245));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        inputBuscar.setBackground(new java.awt.Color(248, 245, 245));
        inputBuscar.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputBuscar.setForeground(new java.awt.Color(51, 51, 51));
        inputBuscar.setBorder(null);
        inputBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBuscarActionPerformed(evt);
            }
        });

        panelDatos.setBackground(new java.awt.Color(248, 245, 245));

        btnNombre.setBackground(new java.awt.Color(248, 245, 245));
        btnNombre.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnNombre.setForeground(new java.awt.Color(51, 51, 51));
        btnNombre.setText("Nombre");
        btnNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNombre.setEnabled(false);
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });

        btnDireccion.setBackground(new java.awt.Color(248, 245, 245));
        btnDireccion.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnDireccion.setForeground(new java.awt.Color(51, 51, 51));
        btnDireccion.setText("Dirección");
        btnDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDireccion.setEnabled(false);
        btnDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionActionPerformed(evt);
            }
        });

        btnEdad.setBackground(new java.awt.Color(248, 245, 245));
        btnEdad.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnEdad.setForeground(new java.awt.Color(51, 51, 51));
        btnEdad.setText("Edad");
        btnEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEdad.setEnabled(false);
        btnEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdadActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 102));
        jLabel6.setText("Datos generales");

        inputNombre.setEditable(false);
        inputNombre.setBackground(new java.awt.Color(248, 245, 245));
        inputNombre.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputNombre.setToolTipText("Nombre");
        inputNombre.setBorder(null);
        inputNombre.setEnabled(false);
        inputNombre.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inputDireccion.setEditable(false);
        inputDireccion.setBackground(new java.awt.Color(248, 245, 245));
        inputDireccion.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputDireccion.setToolTipText("Nombre");
        inputDireccion.setBorder(null);
        inputDireccion.setEnabled(false);
        inputDireccion.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDireccionActionPerformed(evt);
            }
        });

        inputDNI.setEditable(false);
        inputDNI.setBackground(new java.awt.Color(248, 245, 245));
        inputDNI.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputDNI.setToolTipText("Nombre");
        inputDNI.setBorder(null);
        inputDNI.setEnabled(false);
        inputDNI.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDNIActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnDNI.setBackground(new java.awt.Color(248, 245, 245));
        btnDNI.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnDNI.setForeground(new java.awt.Color(51, 51, 51));
        btnDNI.setText("DNI");
        btnDNI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDNI.setEnabled(false);
        btnDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNIActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inputEdad.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputEdad.setBorder(null);
        inputEdad.setEnabled(false);

        grupoGenero.add(inputMasc);
        inputMasc.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputMasc.setToolTipText("");
        inputMasc.setBorder(null);
        inputMasc.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MASC_select.png"))); // NOI18N
        inputMasc.setEnabled(false);
        inputMasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MASC_noSelect.png"))); // NOI18N

        grupoGenero.add(inputOtro);
        inputOtro.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputOtro.setToolTipText("");
        inputOtro.setBorder(null);
        inputOtro.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/OTRO_select.png"))); // NOI18N
        inputOtro.setEnabled(false);
        inputOtro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OTRO_noSelect.png"))); // NOI18N

        grupoGenero.add(inputFem);
        inputFem.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputFem.setToolTipText("");
        inputFem.setBorder(null);
        inputFem.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/FEM_select.png"))); // NOI18N
        inputFem.setEnabled(false);
        inputFem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FEM_noSelect.png"))); // NOI18N

        btnGenero.setBackground(new java.awt.Color(248, 245, 245));
        btnGenero.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnGenero.setForeground(new java.awt.Color(51, 51, 51));
        btnGenero.setText("Género");
        btnGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenero.setEnabled(false);
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });

        panelVehiculo.setBackground(new java.awt.Color(248, 245, 245));
        panelVehiculo.setLayout(new java.awt.CardLayout());

        panelVehiculoSi.setBackground(new java.awt.Color(248, 245, 245));

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 102));
        jLabel15.setText("Vehículo");

        jSeparator25.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator25.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jSeparator26.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator26.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jSeparator27.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator27.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inputMatricula3.setEditable(false);
        inputMatricula3.setBackground(new java.awt.Color(248, 245, 245));
        inputMatricula3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputMatricula3.setToolTipText("Nombre");
        inputMatricula3.setBorder(null);
        inputMatricula3.setEnabled(false);
        inputMatricula3.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputMatricula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMatricula3ActionPerformed(evt);
            }
        });

        btnMatriculaSI.setBackground(new java.awt.Color(248, 245, 245));
        btnMatriculaSI.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnMatriculaSI.setForeground(new java.awt.Color(51, 51, 51));
        btnMatriculaSI.setText("Matrícula");
        btnMatriculaSI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMatriculaSI.setEnabled(false);
        btnMatriculaSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculaSIActionPerformed(evt);
            }
        });

        btnAntiguedadSi.setBackground(new java.awt.Color(248, 245, 245));
        btnAntiguedadSi.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnAntiguedadSi.setForeground(new java.awt.Color(51, 51, 51));
        btnAntiguedadSi.setText("Antigüedad (meses)");
        btnAntiguedadSi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAntiguedadSi.setEnabled(false);
        btnAntiguedadSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntiguedadSiActionPerformed(evt);
            }
        });

        inputAntiguedadSi.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputAntiguedadSi.setBorder(null);
        inputAntiguedadSi.setEnabled(false);

        javax.swing.GroupLayout panelVehiculoSiLayout = new javax.swing.GroupLayout(panelVehiculoSi);
        panelVehiculoSi.setLayout(panelVehiculoSiLayout);
        panelVehiculoSiLayout.setHorizontalGroup(
            panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(btnMatriculaSI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAntiguedadSi, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(inputAntiguedadSi))
                .addGap(29, 29, 29))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 274, Short.MAX_VALUE)
                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 274, Short.MAX_VALUE)))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 274, Short.MAX_VALUE)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 274, Short.MAX_VALUE)))
        );
        panelVehiculoSiLayout.setVerticalGroup(
            panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVehiculoSiLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                        .addComponent(btnAntiguedadSi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(inputAntiguedadSi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(32, 32, 32)
                        .addComponent(btnMatriculaSI, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(inputMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 124, Short.MAX_VALUE)))
            .addGroup(panelVehiculoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVehiculoSiLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 124, Short.MAX_VALUE)))
        );

        panelVehiculo.add(panelVehiculoSi, "panelVehiculoSi");

        panelVehiculoNo.setBackground(new java.awt.Color(248, 245, 245));

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 102));
        jLabel16.setText("Vehículo");

        jLabel22.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("No hay vehículo registrado.");

        javax.swing.GroupLayout panelVehiculoNoLayout = new javax.swing.GroupLayout(panelVehiculoNo);
        panelVehiculoNo.setLayout(panelVehiculoNoLayout);
        panelVehiculoNoLayout.setHorizontalGroup(
            panelVehiculoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoNoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVehiculoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        panelVehiculoNoLayout.setVerticalGroup(
            panelVehiculoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoNoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel16)
                .addGap(26, 26, 26)
                .addComponent(jLabel22)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        panelVehiculo.add(panelVehiculoNo, "panelVehiculoNo");

        panelEspecifico.setLayout(new java.awt.CardLayout());

        panelEmpleado.setBackground(new java.awt.Color(248, 245, 245));

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 102));
        jLabel9.setText("Datos específicos");

        inputIDempleado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputIDempleado.setBorder(null);
        inputIDempleado.setEnabled(false);

        btnID1.setBackground(new java.awt.Color(248, 245, 245));
        btnID1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnID1.setForeground(new java.awt.Color(51, 51, 51));
        btnID1.setText("ID");
        btnID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnID1.setEnabled(false);
        btnID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnID1ActionPerformed(evt);
            }
        });

        btnSueldo.setBackground(new java.awt.Color(248, 245, 245));
        btnSueldo.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnSueldo.setForeground(new java.awt.Color(51, 51, 51));
        btnSueldo.setText("Sueldo");
        btnSueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSueldo.setEnabled(false);
        btnSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSueldoActionPerformed(evt);
            }
        });

        inputSueldo.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputSueldo.setBorder(null);
        inputSueldo.setEnabled(false);

        javax.swing.GroupLayout panelEmpleadoLayout = new javax.swing.GroupLayout(panelEmpleado);
        panelEmpleado.setLayout(panelEmpleadoLayout);
        panelEmpleadoLayout.setHorizontalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(panelEmpleadoLayout.createSequentialGroup()
                        .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        panelEmpleadoLayout.setVerticalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnID1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(inputIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        panelEspecifico.add(panelEmpleado, "panelEmpleado");

        panelCliente.setBackground(new java.awt.Color(248, 245, 245));
        panelCliente.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(255, 204, 102));
        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 102));
        jLabel10.setText("Datos específicos");

        btnID2.setBackground(new java.awt.Color(248, 245, 245));
        btnID2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnID2.setForeground(new java.awt.Color(51, 51, 51));
        btnID2.setText("ID");
        btnID2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnID2ActionPerformed(evt);
            }
        });

        inputIDcliente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputIDcliente.setBorder(null);
        inputIDcliente.setEnabled(false);

        btnVIP.setBackground(new java.awt.Color(248, 245, 245));
        btnVIP.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnVIP.setForeground(new java.awt.Color(51, 51, 51));
        btnVIP.setText("VIP");
        btnVIP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIPActionPerformed(evt);
            }
        });

        noVIP.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        noVIP.setToolTipText("");
        noVIP.setBorder(null);
        noVIP.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/NO_select.png"))); // NOI18N
        noVIP.setEnabled(false);
        noVIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NO_noSelect.png"))); // NOI18N

        siVIP.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        siVIP.setToolTipText("");
        siVIP.setBorder(null);
        siVIP.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_select.png"))); // NOI18N
        siVIP.setEnabled(false);
        siVIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_noSelect.png"))); // NOI18N

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(siVIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noVIP)))))
                .addContainerGap())
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addComponent(btnID2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(inputIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addComponent(btnVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noVIP)
                            .addComponent(siVIP))))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        panelEspecifico.add(panelCliente, "panelCliente");

        btnEliminar.setBackground(new java.awt.Color(255, 204, 102));
        btnEliminar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar.setText("Eliminar persona");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDatosLayout.createSequentialGroup()
                                    .addComponent(btnGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                    .addComponent(inputFem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputMasc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputOtro)))
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(inputDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(panelEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(btnGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputOtro)
                                    .addComponent(inputMasc)
                                    .addComponent(inputFem)))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33)
                                .addComponent(btnDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                .addComponent(btnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(inputEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(btnNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addComponent(btnDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inputBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, 1289, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        btnBuscar.setSelected(true);

        try {
            try {
                personaSeleccionada = ControladorPersona.getPersonaByDNI((String) inputBuscar.getSelectedItem());
            } catch (DAO_Excep ex) {
                Logger.getLogger(DarBaja.class.getName()).log(Level.SEVERE, null, ex);
            }
            inputDNI.setText(personaSeleccionada.getDNI());
            inputNombre.setText(personaSeleccionada.getNombre());
            inputDireccion.setText(personaSeleccionada.getDireccion());
            inputEdad.setValue(personaSeleccionada.getEdad());

            switch (personaSeleccionada.getGenero()) {
                case 'f':
                    inputFem.setSelected(true);
                    break;
                case 'm':
                    inputMasc.setSelected(true);
                    break;
                case 'o':
                    inputOtro.setSelected(true);
                    break;
                default:
                    break;
            }

            //------------------------------------------------------------------
            if (!(personaSeleccionada.getVehiculo() == null)) {
                vehiculoLayout.show(panelVehiculo, "panelVehiculoSi");

                inputMatricula3.setText(personaSeleccionada.getVehiculo().getMATRICULA());
                inputAntiguedadSi.setValue(personaSeleccionada.getVehiculo().getAntiguedad());

            } else {
                vehiculoLayout.show(panelVehiculo, "panelVehiculoNo");
            }

            //------------------------------------------------------------------
            if (personaSeleccionada instanceof Empleado) {
                tipoLayout.show(panelEspecifico, "panelEmpleado");

                Empleado e = (Empleado) personaSeleccionada;
                inputIDempleado.setValue(e.getID_EMPLEADO());
                inputSueldo.setValue(e.getSueldo());

            } else if (personaSeleccionada instanceof Cliente) {
                tipoLayout.show(panelEspecifico, "panelCliente");

                Cliente c = (Cliente) personaSeleccionada;
                inputIDcliente.setValue(c.getID_CLIENTE());

                if (c.isVip()) {
                    siVIP.setSelected(true);
                } else {
                    noVIP.setSelected(true);
                }
            }

        } catch (excepcionPersona ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error cargando personas.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void inputBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBuscarActionPerformed

    }//GEN-LAST:event_inputBuscarActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionActionPerformed

    private void btnEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdadActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionActionPerformed

    private void inputDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDNIActionPerformed

    private void btnDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDNIActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGeneroActionPerformed

    private void inputMatricula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMatricula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMatricula3ActionPerformed

    private void btnMatriculaSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculaSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatriculaSIActionPerformed

    private void btnAntiguedadSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntiguedadSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAntiguedadSiActionPerformed

    private void btnID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnID1ActionPerformed

    private void btnSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSueldoActionPerformed

    private void btnID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnID2ActionPerformed

    private void btnVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVIPActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (btnBuscar.isSelected()) {
            try {
                int result = JOptionPane.showConfirmDialog(null, "¿Confirma que quiere dar de baja a esta persona?", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, "La persona ha sido dada de baja.");
                    try {
                        ControladorPersona.darBaja(personaSeleccionada);
                    } catch (DAO_Excep ex) {
                        Logger.getLogger(DarBaja.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else if (result == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "La persona no ha sido dada de baja.");
                }

            } catch (IOException ex) {
                Logger.getLogger(DarBaja.class.getName()).log(Level.SEVERE, null, ex);
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione a una persona.", "Buscar", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DarBaja dialog = new DarBaja(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntiguedadSi;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDNI;
    private javax.swing.JButton btnDireccion;
    private javax.swing.JButton btnEdad;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenero;
    private javax.swing.JButton btnID1;
    private javax.swing.JButton btnID2;
    private javax.swing.JButton btnMatriculaSI;
    private javax.swing.JButton btnNombre;
    private javax.swing.JButton btnSueldo;
    private javax.swing.JButton btnVIP;
    private javax.swing.ButtonGroup grupoGenero;
    private javax.swing.ButtonGroup grupoVIP;
    private javax.swing.JSpinner inputAntiguedadSi;
    private javax.swing.JComboBox<String> inputBuscar;
    private javax.swing.JTextField inputDNI;
    private javax.swing.JTextField inputDireccion;
    private javax.swing.JSpinner inputEdad;
    private javax.swing.JRadioButton inputFem;
    private javax.swing.JSpinner inputIDcliente;
    private javax.swing.JSpinner inputIDempleado;
    private javax.swing.JRadioButton inputMasc;
    private javax.swing.JTextField inputMatricula3;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JRadioButton inputOtro;
    private javax.swing.JSpinner inputSueldo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton noVIP;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEmpleado;
    private javax.swing.JPanel panelEspecifico;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVehiculo;
    private javax.swing.JPanel panelVehiculoNo;
    private javax.swing.JPanel panelVehiculoSi;
    private javax.swing.JRadioButton siVIP;
    // End of variables declaration//GEN-END:variables
}
