/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ControladorPersona;
import DAO_Controlador.DAOSQL;
import Excepciones.DAO_Excep;
import Excepciones.excepcionVehiculo;
import Modelo.Persona;
import Modelo.Vehiculo;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author JrGam
 */
public class RegistrarVehiculo extends javax.swing.JDialog {

    CardLayout cLayout;
    Vehiculo v = null;

    /**
     * Creates new form RegistrarVehiculo
     */
    public RegistrarVehiculo(java.awt.Dialog owner, boolean modal) {
        super(owner, modal);
        initComponents();

        cLayout = (CardLayout) (panelDatos.getLayout());

        if (noRegistrado.isSelected()) {
            cLayout.show(panelDatos, "registradoNo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRegistrado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        siRegistrado = new javax.swing.JRadioButton();
        noRegistrado = new javax.swing.JRadioButton();
        panelDatos = new javax.swing.JPanel();
        registradoSi = new javax.swing.JPanel();
        inputBuscar4 = new javax.swing.JComboBox<>();
        btnBuscar4 = new javax.swing.JButton();
        registradoNo = new javax.swing.JPanel();
        inputMatricula3 = new javax.swing.JTextField();
        jSeparator49 = new javax.swing.JSeparator();
        inputAntiguedad3 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(248, 245, 245));
        panelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1275, 785));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("VEHÍCULO");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Registre un vehículo.");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("¿El vehículo ha sido registrado anteriormente?");

        grupoRegistrado.add(siRegistrado);
        siRegistrado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        siRegistrado.setToolTipText("");
        siRegistrado.setBorder(null);
        siRegistrado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        siRegistrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_noSelect.png"))); // NOI18N
        siRegistrado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_select.png"))); // NOI18N
        siRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRegistradoActionPerformed(evt);
            }
        });

        grupoRegistrado.add(noRegistrado);
        noRegistrado.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        noRegistrado.setSelected(true);
        noRegistrado.setToolTipText("");
        noRegistrado.setBorder(null);
        noRegistrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NO_noSelect.png"))); // NOI18N
        noRegistrado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/NO_select.png"))); // NOI18N
        noRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRegistradoActionPerformed(evt);
            }
        });

        panelDatos.setLayout(new java.awt.CardLayout());

        registradoSi.setBackground(new java.awt.Color(248, 245, 245));

        inputBuscar4.setBackground(new java.awt.Color(248, 245, 245));
        inputBuscar4.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputBuscar4.setForeground(new java.awt.Color(51, 51, 51));
        inputBuscar4.setBorder(null);
        inputBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBuscar4ActionPerformed(evt);
            }
        });

        btnBuscar4.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscar4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnBuscar4.setForeground(new java.awt.Color(248, 245, 245));
        btnBuscar4.setText("Buscar");
        btnBuscar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registradoSiLayout = new javax.swing.GroupLayout(registradoSi);
        registradoSi.setLayout(registradoSiLayout);
        registradoSiLayout.setHorizontalGroup(
            registradoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registradoSiLayout.createSequentialGroup()
                .addComponent(inputBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        registradoSiLayout.setVerticalGroup(
            registradoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registradoSiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registradoSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        panelDatos.add(registradoSi, "registradoSi");

        registradoNo.setBackground(new java.awt.Color(248, 245, 245));

        inputMatricula3.setBackground(new java.awt.Color(248, 245, 245));
        inputMatricula3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputMatricula3.setToolTipText("Nombre");
        inputMatricula3.setBorder(null);
        inputMatricula3.setSelectionColor(new java.awt.Color(255, 204, 102));
        inputMatricula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMatricula3ActionPerformed(evt);
            }
        });

        jSeparator49.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator49.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inputAntiguedad3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        inputAntiguedad3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        inputAntiguedad3.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Matrícula");

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Antigüedad (meses)");

        javax.swing.GroupLayout registradoNoLayout = new javax.swing.GroupLayout(registradoNo);
        registradoNo.setLayout(registradoNoLayout);
        registradoNoLayout.setHorizontalGroup(
            registradoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registradoNoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registradoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator49, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(registradoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAntiguedad3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );
        registradoNoLayout.setVerticalGroup(
            registradoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registradoNoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registradoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(26, 26, 26)
                .addGroup(registradoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registradoNoLayout.createSequentialGroup()
                        .addComponent(inputAntiguedad3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(registradoNoLayout.createSequentialGroup()
                        .addComponent(inputMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator49, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelDatos.add(registradoNo, "registradoNo");

        btnRegistrar.setBackground(new java.awt.Color(255, 204, 102));
        btnRegistrar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(siRegistrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noRegistrado)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3))
                                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 101, Short.MAX_VALUE))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noRegistrado)
                    .addComponent(siRegistrado))
                .addGap(30, 30, 30)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBuscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBuscar4ActionPerformed

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    private void inputMatricula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMatricula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMatricula3ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        try {
            DAOSQL sql = new DAOSQL();
            ArrayList<Vehiculo> vehiculos = sql.readAll_V();

            if (siRegistrado.isSelected()) {
                if (btnBuscar4.isEnabled()) {
                    if (vehiculos.contains(new Vehiculo((String) inputBuscar4.getSelectedItem()))) {

                        v = vehiculos.get(vehiculos.indexOf(new Vehiculo((String) inputBuscar4.getSelectedItem())));

                        JOptionPane.showMessageDialog(this, "Vehículo registrado.", "Registro de vehículo", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                dispose();
            } else {

                String MATRICULA = inputMatricula3.getText();
                int antiguedad = (int) inputAntiguedad3.getValue();

                if (MATRICULA.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No se pueden dejar campos en blanco.", "Datos vacíos", JOptionPane.WARNING_MESSAGE);
                    dispose();
                } else {

                    try {

                        MATRICULA = ControladorPersona.validarMatricula(MATRICULA);

                        v = new Vehiculo(MATRICULA, antiguedad);

                        try {
                            ControladorPersona.altaVehiculo(v);

                            JOptionPane.showMessageDialog(this, "Vehículo registrado.", "Registro de vehículo", JOptionPane.INFORMATION_MESSAGE);
                        } catch (excepcionVehiculo ex) {
                            Logger.getLogger(RegistrarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (excepcionVehiculo ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Registro de vehículo.", JOptionPane.WARNING_MESSAGE);
                    }

                    dispose();
                }
            }
        } catch (DAO_Excep ex) {
            Logger.getLogger(RegistrarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void siRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRegistradoActionPerformed
        try {
            if (ControladorPersona.getVehiculos().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay vehículos registrados.", "Sin vehículos", JOptionPane.INFORMATION_MESSAGE);
                noRegistrado.setSelected(true);
            } else {
                cLayout.show(panelDatos, "registradoSi");
                
                System.out.println("test");

                try {
//                    v = null;

                    ArrayList<Vehiculo> vehiculos = ControladorPersona.getVehiculos();

                    System.out.println("lista" + vehiculos);
                    for (Vehiculo v : vehiculos) {
                        inputBuscar4.addItem(v.getMATRICULA());
                    }
                } catch (DAO_Excep ex) {
                    Logger.getLogger(BuscarDNI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (DAO_Excep ex) {
            Logger.getLogger(RegistrarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siRegistradoActionPerformed

    private void noRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRegistradoActionPerformed
        cLayout.show(panelDatos, "registradoNo");
    }//GEN-LAST:event_noRegistradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                RegistrarVehiculo dialog = new RegistrarVehiculo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    public Vehiculo obtenerVehiculo() {
        return v;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup grupoRegistrado;
    private javax.swing.JSpinner inputAntiguedad3;
    private javax.swing.JComboBox<String> inputBuscar4;
    private javax.swing.JTextField inputMatricula3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JRadioButton noRegistrado;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel registradoNo;
    private javax.swing.JPanel registradoSi;
    private javax.swing.JRadioButton siRegistrado;
    // End of variables declaration//GEN-END:variables
}
